# Generated by Django 4.2.8 on 2023-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirationDate',
            field=models.CharField(max_length=255),
        ),
    ]
