# Generated by Django 4.2.8 on 2023-12-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=255),
        ),
    ]
